baseURL = "/"
languageCode = "sk"
title = "Investičný plán Petržalky"
theme = "contrast-hugo"
summaryLength = 25
publishDir = "docs"
googleAnalytics = "UA-130722892-1"
enableRobotsTXT = "true"
[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5
[params]
  description = "Investičný plán Petržalky"
  title = "Investičný plán Petržalky"
  keywords = "Petržalka, investičný plán, projekty, rozpočet, štúdie, zámery"